version: "3"
services:
  frontend:
    build:
      context: ./frontend # Path to your React app's directory
      dockerfile: Dockerfile # Name of your Dockerfile
    ports:
      - "3000:3000" # Maps host port 3000 to container port 3000 (React default)
    volumes:
      - ./frontend/src:/app/src # Optional: Mounts your source code for development
      - /app/node_modules # Prevents node_modules from being overwritten
    environment:
      - CHOKIDAR_USEPOLLING=true # Important for some systems when using volume mounts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge